theme: jekyll-theme-slate
title: New Standards for Benchmarking in Evolutionary Computation Research
description: A workshop for improving benchmarking standards in evolutionary computation research.
show_downloads: false
